### ISSUE TITLE
error when importing geometry

### ISSUE THREAD

**Issue by feber12** [paulus-allods/blender-import#3]
`bpy.context.space_data.recent_folders_active = 0

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\allods_geometry.py", line 88, in execute
    for model_element in parser.get_model_elements():
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\allods_geometry.py", line 284, in get_model_elements
    virtual_offset = float(item.find('virtualOffset').text)
AttributeError: 'NoneType' object has no attribute 'text'

location: <unknown location>:-1

bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 1 object(s)
bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 1 object(s)
Deleted 0 object(s)
bpy.ops.object.delete(use_global=False, confirm=False)
Deleted 1 object(s)
bpy.ops.outliner.item_activate(extend=False, deselect_all=True)
bpy.ops.outliner.item_activate(extend=False, deselect_all=True)
bpy.ops.outliner.item_rename()
bpy.ops.outliner.item_activate(extend=False, deselect_all=True)
Deleted 0 object(s)
bpy.ops.outliner.select_box(tweak=True, xmin=91, xmax=160, ymin=87, ymax=173)
bpy.ops.outliner.delete()
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\allods_geometry.py", line 58, in execute
    bin_parser = BinParser(path.with_suffix('.bin'))
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\allods_geometry.py", line 332, in __init__
    self._read_blobs()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\allods_geometry.py", line 335, in _read_blobs
    content = io.BytesIO(zlib.decompress(open(self.path, 'rb').read()))
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\Nueva carpeta (8)\\Allods_Online_7_0_OWN\\Allods_Online_7_0_OWN\\Server_Starting\\Server_Starting\\game\\game\\data\\data\\Colossus\\ColossusScout.(Geometry).bin'

location: <unknown location>:-1

Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\allods_geometry.py", line 88, in execute
    for model_element in parser.get_model_elements():
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\allods_geometry.py", line 284, in get_model_elements
    virtual_offset = float(item.find('virtualOffset').text)
AttributeError: 'NoneType' object has no attribute 'text'

location: <unknown location>:-1
`

I got this error when importing the model, I have the bin and xdb

**Comment by paulus-allods** [comment]
Hi can you send your xdb file, I guess that the virtualOffset attribute is missing. I'll add some conditions on non-required attributes to avoid crash on some xdbs.

**Comment by tatsuketsueki-droid** [comment]
Hello, I have the same error - 

File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\allods_geometry.py", line 88, in execute
for model_element in parser.get_model_elements():
File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\allods_geometry.py", line 284, in get_model_elements
virtual_offset = float(item.find('virtualOffset').text)
AttributeError: 'NoneType' object has no attribute 'text'

location: :-1

Can you please tell what virtual offset attribute is missing?
